In [2]:
import numpy as np

In [7]:
a=np.array([1,2,3])
b=np.array([(1,2,3,4),(7,8,9,10)],dtype=int)
a,
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [6]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b=np.array([(1,2,3,4),(7,8,9,10)],dtype=int)
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [7]:
b.dtype

dtype('int32')

In [8]:
a.dtype

dtype('int32')

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [16]:
np.random.rand(3,5)

array([[0.17114466, 0.77531295, 0.13939775, 0.31352706, 0.26692282],
       [0.50188355, 0.62691614, 0.24703946, 0.10811232, 0.20521501],
       [0.9288832 , 0.31629461, 0.40751796, 0.46640722, 0.25162686]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
a

[1, 2, 3, 4]

In [55]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [57]:
v=b.reshape(3,1)
v

array([[1],
       [2],
       [3]])

In [58]:
np.copy(b)

array([1, 2, 3])

In [62]:
b.view(dtype="int")

array([1, 2, 3])

In [65]:
#add
np.append(b,4)

array([1, 2, 3, 4])

In [69]:
np.insert(a,4,5)

array([1, 2, 3, 4, 5])

In [71]:
np.insert(a,4,6)

array([1, 2, 3, 4, 6])

In [77]:
c=np.array([6,7,8])
c

array([6, 7, 8])

In [91]:
#Delete

np.delete(c,2)

array([6, 7])

In [94]:
z=np.delete(c,1)
z

array([6, 8])

In [88]:
c

array([6, 7, 8])

In [97]:
c=np.delete(c,1)
c

array([6, 8])

In [98]:
c

array([6, 8])

In [102]:
#combining
d=np.array([1,2,3])
d

array([1, 2, 3])

In [103]:
e=np.array([4,5,6])
e

array([4, 5, 6])

In [104]:
np.concatenate((d,e),axis=0)


array([1, 2, 3, 4, 5, 6])

In [106]:
np.concatenate((d,e),axis=0)

array([1, 2, 3, 4, 5, 6])

In [107]:
Splitting
np.split(d,3)

[array([1]), array([2]), array([3])]

In [110]:
np.split(e,3)

[array([4]), array([5]), array([6])]

In [111]:
#indexing
d[1]=2
d

array([1, 2, 3])