In [1]:
a=[[1,2,4],[5,8,9]]
a

[[1, 2, 4], [5, 8, 9]]

In [2]:
b=[[6,3,7],[10,13,15]]
b

[[6, 3, 7], [10, 13, 15]]

In [4]:
import numpy as np

In [5]:
#hstack to print horizontal array
c=np.hstack((a,b))
c

array([[ 1,  2,  4,  6,  3,  7],
       [ 5,  8,  9, 10, 13, 15]])

In [6]:
#vstack to print vertical array
d=np.vstack((a,b))
d

array([[ 1,  2,  4],
       [ 5,  8,  9],
       [ 6,  3,  7],
       [10, 13, 15]])

In [7]:
#arange
e=np.arange(1,15)
e

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
#to print difference(table)
f=np.arange(13,131,13)
f

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [10]:
#linear space(linspace) to divide array in equal part
g=np.linspace(0,4,num=10)
g

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [12]:
h=np.array([(2,4,6),(1,3,5)])
h

array([[2, 4, 6],
       [1, 3, 5]])

In [18]:
#slicing
h[0:2]


array([[2, 4, 6],
       [1, 3, 5]])

In [19]:
h[0:1]

array([[2, 4, 6]])

In [17]:
#indexing for rows
h[0]

array([2, 4, 6])

In [16]:
h[1]

array([1, 3, 5])

In [20]:
#indexing for columns
h[:,0]

array([2, 1])

In [21]:
h[:,2]

array([6, 5])

In [22]:
#indexing for rows & columns
h[1,2]

5

In [23]:
h[0,1]

4

In [24]:
x=np.array([(1,1,1,1),(1,1,1,1),(1,1,1,1),(1,1,1,1)])
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
y=np.ones((4,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
#to print identity matrix
z=np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#to add/sub value in values array
h+=3
h

array([[ 7,  9, 11],
       [ 6,  8, 10]])

In [33]:
h-=1
h

array([[5, 7, 9],
       [4, 6, 8]])

In [36]:
#for max/min values
h.min()

4

In [37]:
h.max()

9

In [38]:
h

array([[5, 7, 9],
       [4, 6, 8]])

In [42]:
r = np.random.randint(0,20,size=(3,3))
r

array([[ 3, 16,  8],
       [ 3, 11,  6],
       [ 1,  3,  0]])

In [46]:
#to reshape array
r.reshape(9,1)

array([[ 3],
       [16],
       [ 8],
       [ 3],
       [11],
       [ 6],
       [ 1],
       [ 3],
       [ 0]])

In [49]:
c.reshape(4,3)

array([[ 1,  2,  4],
       [ 6,  3,  7],
       [ 5,  8,  9],
       [10, 13, 15]])

In [50]:
c[:,1]

array([2, 8])

In [51]:
#to make new array contains addition of given arrays
er=np.add(a,b)
er

array([[ 7,  5, 11],
       [15, 21, 24]])

In [54]:
#to swap values of array
ef=er.T
ef

array([[ 7, 15],
       [ 5, 21],
       [11, 24]])