In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
ir =pd.read_csv('iris.csv')

In [4]:
ir

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
ir['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [6]:
x=ir.iloc[:,0:4].values #filter on Independent Variable

In [7]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y=ir.iloc[:,4].values  #filter on dependent variable

In [9]:
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
labelencoder_y = LabelEncoder()

In [12]:
y=labelencoder_y.fit_transform(y)

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [16]:
print("xtrain",x_train)
print("ytrain",y_train)
print("xtest",x_test)
print("ytest",y_test)

xtrain [[6.2 3.4 5.4 2.3]
 [6.7 3.3 5.7 2.1]
 [6.  3.  4.8 1.8]
 [6.1 3.  4.6 1.4]
 [4.8 3.1 1.6 0.2]
 [5.6 3.  4.1 1.3]
 [6.4 2.9 4.3 1.3]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [5.  2.  3.5 1. ]
 [6.9 3.1 4.9 1.5]
 [5.6 2.7 4.2 1.3]
 [4.9 3.  1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.9 3.  5.1 1.8]
 [6.7 3.1 4.4 1.4]
 [4.8 3.  1.4 0.1]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [5.2 2.7 3.9 1.4]
 [5.4 3.4 1.5 0.4]
 [4.9 3.1 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.7 2.8 4.5 1.3]
 [5.  3.5 1.6 0.6]
 [5.  3.6 1.4 0.2]
 [5.7 2.9 4.2 1.3]
 [5.8 2.6 4.  1.2]
 [7.9 3.8 6.4 2. ]
 [6.3 3.3 6.  2.5]
 [6.1 2.9 4.7 1.4]
 [5.9 3.2 4.8 1.8]
 [7.2 3.  5.8 1.6]
 [5.8 2.7 5.1 1.9]
 [6.7 3.1 4.7 1.5]
 [5.5 4.2 1.4 0.2]
 [6.3 2.9 5.6 1.8]
 [4.9 2.4 3.3 1. ]
 [5.5 2.5 4.  1.3]
 [6.9 3.1 5.1 2.3]
 [6.1 2.8 4.7 1.2]
 [7.1 3.  5.9 2.1]
 [6.1 2.6 5.6 1.4]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [5.  3.  1.6 0.2]
 [6.7 3.1 5.6 2.4]
 [5.8 2.7 4.1 1. ]
 [6.  2.9 4.5 1.5]
 [6.7 3.  5.  1.7]
 [4.8 3.4 1.6 0.2]
 [6.8 2.8 4.8 1.4]
 [5. 

In [17]:
print("Xtrain_Size:",x_train.size)
print("ytrain_Size:",y_train.size)
print("Xtest_Size:",x_test.size)
print("ytest_Size:",y_test.size)

Xtrain_Size: 420
ytrain_Size: 105
Xtest_Size: 180
ytest_Size: 45


In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [20]:
y_pred = logmodel.predict(x_test)

In [21]:
y_pred

array([0, 2, 2, 0, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2,
       0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 2, 0,
       0])

In [22]:

np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [23]:


from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0,  9,  1],
       [ 0,  2, 18]], dtype=int64)

In [25]:
logmodel.score(x_test,y_test)

0.9333333333333333

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
classifier_Knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [28]:
classifier_Knn

KNeighborsClassifier()

In [29]:
classifier_Knn.fit(x_train,y_train)

KNeighborsClassifier()

In [30]:
y_pred_knn=classifier_Knn.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [31]:
y_pred_knn

array([0, 2, 2, 0, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2,
       0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 0, 2, 1, 2, 2, 1, 2, 0, 2, 2, 2, 0,
       0])

In [32]:
confusion_matrix(y_test,y_pred_knn)

array([[15,  0,  0],
       [ 0,  9,  1],
       [ 0,  1, 19]], dtype=int64)

In [33]:
classifier_Knn.score(x_test,y_test)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9555555555555556

In [34]:
import numpy as np
import pandas as pd

In [35]:
from sklearn.naive_bayes import GaussianNB

In [36]:
classifier_nb = GaussianNB()

In [37]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [38]:
y_pred = classifier_nb.predict(x_test)

In [39]:
y_pred

array([0, 2, 2, 0, 2, 2, 2, 1, 2, 1, 0, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2,
       0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 1, 1, 2, 1, 2, 0, 2, 2, 2, 0,
       0])

In [40]:
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [43]:
classifier_nb.score(x_test,y_test)

0.9555555555555556

In [44]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy_score(y_pred,y_test)

0.9555555555555556

In [54]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 10,  0],
       [ 0,  2, 18]], dtype=int64)

In [56]:
from sklearn.svm import SVC

In [57]:
classifier_svc_sig =SVC(kernel ='sigmoid')

In [58]:
classifier_svc_sig

SVC(kernel='sigmoid')

In [62]:
classifier_svc_sig.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [63]:
y_pred_svc =classifier_svc_sig.predict(x_test)

In [65]:
y_pred_svc

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

In [66]:
y_test

array([0, 2, 2, 0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2,
       0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 1, 2, 2, 1, 2, 0, 2, 2, 2, 0,
       0])

In [67]:
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [68]:
confusion_matrix(y_test,y_pred_svc)

array([[ 0, 15,  0],
       [ 0, 10,  0],
       [ 0, 20,  0]], dtype=int64)

In [69]:
classifier_svc_sig.score(x_test,y_test)

0.2222222222222222

In [ ]:
#sigmoid = 0.2222222