In [1]:
import pandas as pd

In [2]:
a=pd.read_csv('tested.csv')
a

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [1]:
import numpy as np

In [4]:
a=([1,2],[3,4])

In [5]:
a

([1, 2], [3, 4])

In [6]:
b=np.array(a)
b

array([[1, 2],
       [3, 4]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 2)

In [9]:
b.size

4

In [10]:
b.itemsize

4

In [11]:
b.dtype

dtype('int32')

In [12]:
b.data

In [13]:
#single dimension array
c=np.array([1,2,3])
c

array([1, 2, 3])

In [14]:
c.ndim

1

In [15]:
c.shape

(3,)

In [16]:
c.size

3

In [17]:
c.data

In [18]:
c.dtype

dtype('int32')

In [22]:
d=np.array([[[1.0,2.0],[3.0,4.0],[5.0,6.0],[7.0,8.0]]])
d

array([[[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]])

In [23]:
d.ndim

3

In [24]:
d.dtype

dtype('float64')

In [26]:
e=np.full((3,2),2)
e

array([[2, 2],
       [2, 2],
       [2, 2]])

In [30]:
e=np.ones((3,4))
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
e.dtype

dtype('float64')

In [3]:
import numpy as np
#sum of third coloumn

def sum_third_column(arr):
    return np.sum(arr[:,2])

def sum_second_column(arr):
    return np.sum(arr[:,1])

def sum_first_column(arr):
    return np.sum(arr[:,0])

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [5]:
sum_third_column(arr)

18

In [6]:
sum_second_column(arr)

15

In [9]:
sum_first_column(arr)

12

In [43]:
def transpose(arr):
    return np.transpose(arr)

In [44]:
transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
def average(arr):
    return np.mean(arr)
average(arr)

5.0

In [10]:
arr1=np.array([[10,11,12],[13,14,15],[16,17,18]])
arr1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [49]:
def dot_product(arr,arr1):
    return np.dot(arr, arr1)
dot_product(arr,arr1)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
def concatenate(arr,arr1):
    return np.concatenate((arr, arr1))

concatenate(arr,arr1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
def add(arr, arr1):
    return np.add(arr,arr1)

add(arr, arr1)

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [62]:
def subtract(arr,arr1):
    return np.subtract(arr,arr1)
subtract(arr,arr1)

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [63]:
def multiply(arr,arr1):
    return np.multiply(arr,arr1)
multiply(arr,arr1)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [65]:
def divide(arr1,arr):
    return np.divide(arr1,arr)
divide(arr1,arr)

array([[10.        ,  5.5       ,  4.        ],
       [ 3.25      ,  2.8       ,  2.5       ],
       [ 2.28571429,  2.125     ,  2.        ]])

In [8]:
def sqrt(arr):
    return np.sqrt(arr)
sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [11]:
def exp(arr1):
    return np.exp(arr1)
exp(arr1)

array([[2.20264658e+04, 5.98741417e+04, 1.62754791e+05],
       [4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07]])

In [12]:
arr==arr1

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
ar=([[1,2],[3,4]])
ar1=([[1,2],[3,4]])

ar==ar1

True

In [17]:
def sum(ar):
    return np.sum(ar)
sum(ar)

10

In [18]:
def max(ar):
    return np.max(ar)
max(ar)

4

In [20]:
def min(ar1):
    return np.min(ar1)
min(ar1)

1

In [23]:
#which index is maximum
def index_of_max(ar):
    return np.argmax(ar)
index_of_max(ar)

3

In [26]:
def mean(ar):
    return np.mean(ar)
mean(ar)

2.5

In [30]:
def median(ar1):
    return np.median(ar1)
median(ar1)

2.5

In [31]:
from scipy import stats as st

In [32]:
ab=([1,2,31,1,1,23,21,2,1,1,1])
print(st.mode(ab))

ModeResult(mode=array([1]), count=array([6]))


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1928\1195406691.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print(st.mode(ab))


In [39]:
ha=np.array([[1,2],[3,4],[5,6]])
va=np.array([[11,12],[13,14],[15,16]])

In [40]:
f=np.hstack((ha,va))
f

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [42]:
g=np.vstack((ha,va))
g

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [47]:
h=np.arange(2,20,2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
i=np.arange(12,120,12)
i

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108])

In [50]:
##swaping

sa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Before Swaping:")
print(sa)

temp=np.copy(sa[0])
sa[0]=sa[2]
sa[2]=temp

print("After swaping:")
print(sa)

Before Swaping:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After swaping:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [55]:
p=np.random.randint(0,10,size=(2,4))
print(p)
print(p.shape)
print("After Reshape")
q=p.reshape(4,2)
print(q)

[[7 8 6 7]
 [1 9 0 3]]
(2, 4)
After Reshape
[[7 8]
 [6 7]
 [1 9]
 [0 3]]


In [56]:
j=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(j)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [58]:
j[0,5]

6

In [60]:
j[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [61]:
j[:,1]

array([2, 9])

In [65]:
np.append(j,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20])

In [66]:
np.insert(j,1,30)

array([ 1, 30,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
np.delete(j,1,axis=0)

array([[1, 2, 3, 4, 5, 6, 7]])

In [80]:
j=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
j

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [86]:
j[0,3]=4
j

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [87]:
j

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [88]:
i=np.array([[1,2,3],[4,5,6],[7,8,9]])
i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
i[2,1]=10

In [90]:
i

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 10,  9]])

In [98]:
k=np.array([1,2,3,4,5,6,7,8,9])
k
np.split(k,9)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9])]

In [1]:
import pandas as pd


In [11]:
Name = ['js','ks','ws']
Marks = [70,90,80]
ef=pd.Series(data=Marks)
ef

0    70
1    90
2    80
dtype: int64

In [12]:
type(ef)

pandas.core.series.Series

In [13]:
Student={'Name':Name,'Marks':Marks}
Student

{'Name': ['js', 'ks', 'ws'], 'Marks': [70, 90, 80]}

In [14]:
type(Student)

dict

In [15]:
de=pd.DataFrame(Student)
de

Name  Marks
0   js     70
1   ks     90
2   ws     80

In [16]:
de.shape

(3, 2)

In [17]:
de.info

<bound method DataFrame.info of   Name  Marks
0   js     70
1   ks     90
2   ws     80>

In [18]:
de.describe

<bound method NDFrame.describe of   Name  Marks
0   js     70
1   ks     90
2   ws     80>

In [20]:
de.head(2)

Name  Marks
0   js     70
1   ks     90

In [24]:
de.tail(1)

Name  Marks
2   ws     80

In [29]:
de.columns

Index(['Name', 'Marks'], dtype='object')

In [33]:
a=pd.read_csv('tested.csv')
a

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [34]:
a.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [35]:
a[['PassengerId','Pclass','Name','Ticket']]

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

                 Ticket  
0                330911  
1                363272  
2                240276  
3                315154  
4               3101298  
..                  ...  
413           A.5. 3236  
414            PC 17758  
415  SOTON/O.Q. 3101262  
416              359309  
417                2668  

[418 rows x 4 columns]

In [36]:
a.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                     

In [37]:
a.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                       

In [52]:
# a[(a['Pclass']>2 & (a['Ticket']>330911))]
# a
df=a[(a['Pclass']<2 & (a['Age']>22.0))]
df

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [48]:
a

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [49]:
df=a.drop(columns=['Parch'])

In [50]:
df

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  \
0                                Kelly, Mr. James    male  34.5      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   
2                       Myles, Mr. Thomas Francis    male  62.0      0   
3                                Wirz, Mr. Albert    male  27.0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1   
..                                            ...     ...   ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0   
416                           Ware, Mr. Frederick    male   NaN      0   
417                      Peter, Master. Michael J    male   NaN      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [59]:
a

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Embarked  
0                330911    7.8292        Q  
1                363272    7.0000        S  
2                240276    9.6875        Q  
3                315154    8.6625        S  
4               3101298   12.2875        S  
..                  ...       ...      ...  
413           A.5. 3236    8.0500        S  
414            PC 17758  108.9000        C  
415  SOTON/O.Q. 3101262    7.2500        S  
416              359309    8.0500        S  
417                2668   22.3583        C  

[418 rows x 11 columns]

In [60]:
a=pd.read_csv('tested.csv',index_col='Name')

In [61]:
a

PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                             1309         0       3   

                                                 Sex   Age  SibSp  Parch  \
Name                                                                       
Kelly, Mr. James                                male  34.5      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.0      1      0   
Myles, Mr. Thomas Francis                       male  62.0      0      0   
Wirz, Mr. Albert                                male  27.0      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
...                                              ...   ...    ...    ...   
Spector, Mr. Woolf                              male   NaN      0      0   
Oliva y Ocana, Dona. Fermina                  female  39.0      0      0   
Saether, Mr. Simon Sivertsen                    male  38.5      0      0   
Ware, Mr. Frederick                             male   NaN      0      0   
Peter, Master. Michael J                        male   NaN      1      1   

                                                          Ticket      Fare  \
Name                                                                         
Kelly, Mr. James                                          330911    7.8292   
Wilkes, Mrs. James (Ellen Needs)                          363272    7.0000   
Myles, Mr. Thomas Francis                                 240276    9.6875   
Wirz, Mr. Albert                                          315154    8.6625   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)             3101298   12.2875   
...                                                          ...       ...   
Spector, Mr. Woolf                                     A.5. 3236    8.0500   
Oliva y Ocana, Dona. Fermina                            PC 17758  108.9000   
Saether, Mr. Simon Sivertsen                  SOTON/O.Q. 3101262    7.2500   
Ware, Mr. Frederick                                       359309    8.0500   
Peter, Master. Michael J                                    2668   22.3583   

                                             Cabin Embarked  
Name                                                         
Kelly, Mr. James                               NaN        Q  
Wilkes, Mrs. James (Ellen Needs)               NaN        S  
Myles, Mr. Thomas Francis                      NaN        Q  
Wirz, Mr. Albert                               NaN        S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)   NaN        S  
...                                            ...      ...  
Spector, Mr. Woolf                             NaN        S  
Oliva y Ocana, Dona. Fermina                  C105        C  
Saether, Mr. Simon Sivertsen                   NaN        S  
Ware, Mr. Frederick                            NaN        S  
Peter, Master. Michael J                       NaN        C  

[418 rows x 11 columns]

In [62]:
a.shape

(418, 11)

In [63]:
a.head(10)

PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
Svensson, Mr. Johan Cervin                            897         0       3   
Connolly, Miss. Kate                                  898         1       3   
Caldwell, Mr. Albert Francis                          899         0       2   
Abrahim, Mrs. Joseph (Sophie Halaut Easu)             900         1       3   
Davies, Mr. John Samuel                               901         0       3   

                                                 Sex   Age  SibSp  Parch  \
Name                                                                       
Kelly, Mr. James                                male  34.5      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.0      1      0   
Myles, Mr. Thomas Francis                       male  62.0      0      0   
Wirz, Mr. Albert                                male  27.0      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
Svensson, Mr. Johan Cervin                      male  14.0      0      0   
Connolly, Miss. Kate                          female  30.0      0      0   
Caldwell, Mr. Albert Francis                    male  26.0      1      1   
Abrahim, Mrs. Joseph (Sophie Halaut Easu)     female  18.0      0      0   
Davies, Mr. John Samuel                         male  21.0      2      0   

                                                 Ticket     Fare Cabin  \
Name                                                                     
Kelly, Mr. James                                 330911   7.8292   NaN   
Wilkes, Mrs. James (Ellen Needs)                 363272   7.0000   NaN   
Myles, Mr. Thomas Francis                        240276   9.6875   NaN   
Wirz, Mr. Albert                                 315154   8.6625   NaN   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)    3101298  12.2875   NaN   
Svensson, Mr. Johan Cervin                         7538   9.2250   NaN   
Connolly, Miss. Kate                             330972   7.6292   NaN   
Caldwell, Mr. Albert Francis                     248738  29.0000   NaN   
Abrahim, Mrs. Joseph (Sophie Halaut Easu)          2657   7.2292   NaN   
Davies, Mr. John Samuel                       A/4 48871  24.1500   NaN   

                                             Embarked  
Name                                                   
Kelly, Mr. James                                    Q  
Wilkes, Mrs. James (Ellen Needs)                    S  
Myles, Mr. Thomas Francis                           Q  
Wirz, Mr. Albert                                    S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)        S  
Svensson, Mr. Johan Cervin                          S  
Connolly, Miss. Kate                                Q  
Caldwell, Mr. Albert Francis                        S  
Abrahim, Mrs. Joseph (Sophie Halaut Easu)           C  
Davies, Mr. John Samuel                             S

In [64]:
a.tail(10)

PassengerId  Survived  \
Name                                                                     
Riordan, Miss. Johanna Hannah""                         1300         1   
Peacock, Miss. Treasteall                               1301         1   
Naughton, Miss. Hannah                                  1302         1   
Minahan, Mrs. William Edward (Lillian E Thorpe)         1303         1   
Henriksson, Miss. Jenny Lovisa                          1304         1   
Spector, Mr. Woolf                                      1305         0   
Oliva y Ocana, Dona. Fermina                            1306         1   
Saether, Mr. Simon Sivertsen                            1307         0   
Ware, Mr. Frederick                                     1308         0   
Peter, Master. Michael J                                1309         0   

                                                 Pclass     Sex   Age  SibSp  \
Name                                                                           
Riordan, Miss. Johanna Hannah""                       3  female   NaN      0   
Peacock, Miss. Treasteall                             3  female   3.0      1   
Naughton, Miss. Hannah                                3  female   NaN      0   
Minahan, Mrs. William Edward (Lillian E Thorpe)       1  female  37.0      1   
Henriksson, Miss. Jenny Lovisa                        3  female  28.0      0   
Spector, Mr. Woolf                                    3    male   NaN      0   
Oliva y Ocana, Dona. Fermina                          1  female  39.0      0   
Saether, Mr. Simon Sivertsen                          3    male  38.5      0   
Ware, Mr. Frederick                                   3    male   NaN      0   
Peter, Master. Michael J                              3    male   NaN      1   

                                                 Parch              Ticket  \
Name                                                                         
Riordan, Miss. Johanna Hannah""                      0              334915   
Peacock, Miss. Treasteall                            1  SOTON/O.Q. 3101315   
Naughton, Miss. Hannah                               0              365237   
Minahan, Mrs. William Edward (Lillian E Thorpe)      0               19928   
Henriksson, Miss. Jenny Lovisa                       0              347086   
Spector, Mr. Woolf                                   0           A.5. 3236   
Oliva y Ocana, Dona. Fermina                         0            PC 17758   
Saether, Mr. Simon Sivertsen                         0  SOTON/O.Q. 3101262   
Ware, Mr. Frederick                                  0              359309   
Peter, Master. Michael J                             1                2668   

                                                     Fare Cabin Embarked  
Name                                                                      
Riordan, Miss. Johanna Hannah""                    7.7208   NaN        Q  
Peacock, Miss. Treasteall                         13.7750   NaN        S  
Naughton, Miss. Hannah                             7.7500   NaN        Q  
Minahan, Mrs. William Edward (Lillian E Thorpe)   90.0000   C78        Q  
Henriksson, Miss. Jenny Lovisa                     7.7750   NaN        S  
Spector, Mr. Woolf                                 8.0500   NaN        S  
Oliva y Ocana, Dona. Fermina                     108.9000  C105        C  
Saether, Mr. Simon Sivertsen                       7.2500   NaN        S  
Ware, Mr. Frederick                                8.0500   NaN        S  
Peter, Master. Michael J                          22.3583   NaN        C

In [65]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 418 entries, Kelly, Mr. James to Peter, Master. Michael J
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 39.2+ KB


In [66]:
a.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.481622    0.841838   14.181209    0.896760   
min     892.000000    0.000000    1.000000    0.170000    0.000000   
25%     996.250000    0.000000    1.000000   21.000000    0.000000   
50%    1100.500000    0.000000    3.000000   27.000000    0.000000   
75%    1204.750000    1.000000    3.000000   39.000000    1.000000   
max    1309.000000    1.000000    3.000000   76.000000    8.000000   

            Parch        Fare  
count  418.000000  417.000000  
mean     0.392344   35.627188  
std      0.981429   55.907576  
min      0.000000    0.000000  
25%      0.000000    7.895800  
50%      0.000000   14.454200  
75%      0.000000   31.500000  
max      9.000000  512.329200

In [67]:
clist=a.columns

In [68]:
clist

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [69]:
a.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [73]:
r=a['Age']
r

Name
Kelly, Mr. James                                34.5
Wilkes, Mrs. James (Ellen Needs)                47.0
Myles, Mr. Thomas Francis                       62.0
Wirz, Mr. Albert                                27.0
Hirvonen, Mrs. Alexander (Helga E Lindqvist)    22.0
                                                ... 
Spector, Mr. Woolf                               NaN
Oliva y Ocana, Dona. Fermina                    39.0
Saether, Mr. Simon Sivertsen                    38.5
Ware, Mr. Frederick                              NaN
Peter, Master. Michael J                         NaN
Name: Age, Length: 418, dtype: float64

In [74]:
type(r)

pandas.core.series.Series

In [75]:
rmean=r.mean()
rmean

30.272590361445783

In [76]:
r.fillna(rmean,inplace=True)
r

Name
Kelly, Mr. James                                34.50000
Wilkes, Mrs. James (Ellen Needs)                47.00000
Myles, Mr. Thomas Francis                       62.00000
Wirz, Mr. Albert                                27.00000
Hirvonen, Mrs. Alexander (Helga E Lindqvist)    22.00000
                                                  ...   
Spector, Mr. Woolf                              30.27259
Oliva y Ocana, Dona. Fermina                    39.00000
Saether, Mr. Simon Sivertsen                    38.50000
Ware, Mr. Frederick                             30.27259
Peter, Master. Michael J                        30.27259
Name: Age, Length: 418, dtype: float64

In [78]:
a
a.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [79]:
g=a['Fare']
g

Name
Kelly, Mr. James                                  7.8292
Wilkes, Mrs. James (Ellen Needs)                  7.0000
Myles, Mr. Thomas Francis                         9.6875
Wirz, Mr. Albert                                  8.6625
Hirvonen, Mrs. Alexander (Helga E Lindqvist)     12.2875
                                                  ...   
Spector, Mr. Woolf                                8.0500
Oliva y Ocana, Dona. Fermina                    108.9000
Saether, Mr. Simon Sivertsen                      7.2500
Ware, Mr. Frederick                               8.0500
Peter, Master. Michael J                         22.3583
Name: Fare, Length: 418, dtype: float64

In [80]:
type(g)

pandas.core.series.Series

In [81]:
gmean=g.mean()
gmean

35.6271884892086

In [83]:
g.fillna(gmean,inplace=True)
g

Name
Kelly, Mr. James                                  7.8292
Wilkes, Mrs. James (Ellen Needs)                  7.0000
Myles, Mr. Thomas Francis                         9.6875
Wirz, Mr. Albert                                  8.6625
Hirvonen, Mrs. Alexander (Helga E Lindqvist)     12.2875
                                                  ...   
Spector, Mr. Woolf                                8.0500
Oliva y Ocana, Dona. Fermina                    108.9000
Saether, Mr. Simon Sivertsen                      7.2500
Ware, Mr. Frederick                               8.0500
Peter, Master. Michael J                         22.3583
Name: Fare, Length: 418, dtype: float64

In [86]:
a.isnull().sum()



PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [89]:
mdf=a.iloc[2]
mdf

PassengerId       894
Survived            0
Pclass              2
Sex              male
Age              62.0
SibSp               0
Parch               0
Ticket         240276
Fare           9.6875
Cabin             NaN
Embarked            Q
Name: Myles, Mr. Thomas Francis, dtype: object

In [95]:
a.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [98]:
a['Cabin'].fillna(method ='ffill',limit=327,inplace=True)
a

PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                             1309         0       3   

                                                 Sex       Age  SibSp  Parch  \
Name                                                                           
Kelly, Mr. James                                male  34.50000      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.00000      1      0   
Myles, Mr. Thomas Francis                       male  62.00000      0      0   
Wirz, Mr. Albert                                male  27.00000      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1      1   
...                                              ...       ...    ...    ...   
Spector, Mr. Woolf                              male  30.27259      0      0   
Oliva y Ocana, Dona. Fermina                  female  39.00000      0      0   
Saether, Mr. Simon Sivertsen                    male  38.50000      0      0   
Ware, Mr. Frederick                             male  30.27259      0      0   
Peter, Master. Michael J                        male  30.27259      1      1   

                                                          Ticket      Fare  \
Name                                                                         
Kelly, Mr. James                                          330911    7.8292   
Wilkes, Mrs. James (Ellen Needs)                          363272    7.0000   
Myles, Mr. Thomas Francis                                 240276    9.6875   
Wirz, Mr. Albert                                          315154    8.6625   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)             3101298   12.2875   
...                                                          ...       ...   
Spector, Mr. Woolf                                     A.5. 3236    8.0500   
Oliva y Ocana, Dona. Fermina                            PC 17758  108.9000   
Saether, Mr. Simon Sivertsen                  SOTON/O.Q. 3101262    7.2500   
Ware, Mr. Frederick                                       359309    8.0500   
Peter, Master. Michael J                                    2668   22.3583   

                                             Cabin Embarked  
Name                                                         
Kelly, Mr. James                               NaN        Q  
Wilkes, Mrs. James (Ellen Needs)               NaN        S  
Myles, Mr. Thomas Francis                      NaN        Q  
Wirz, Mr. Albert                               NaN        S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)   NaN        S  
...                                            ...      ...  
Spector, Mr. Woolf                             C78        S  
Oliva y Ocana, Dona. Fermina                  C105        C  
Saether, Mr. Simon Sivertsen                  C105        S  
Ware, Mr. Frederick                           C105        S  
Peter, Master. Michael J                      C105        C  

[418 rows x 11 columns]

In [99]:
a.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          12
Embarked        0
dtype: int64

In [106]:
a['Cabin'].fillna(method ='ffill',limit=500,inplace=True)


In [107]:
a.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          12
Embarked        0
dtype: int64

In [108]:
for item in a:
    print(a)

                                              PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                            

                                              PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                            

In [109]:
a.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Sex             0
Age             0
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin          12
Embarked        0
dtype: int64

In [110]:
type(a)

pandas.core.frame.DataFrame

In [111]:
a.fillna('',inplace=True)

In [112]:
a

PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                             1309         0       3   

                                                 Sex       Age  SibSp  Parch  \
Name                                                                           
Kelly, Mr. James                                male  34.50000      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.00000      1      0   
Myles, Mr. Thomas Francis                       male  62.00000      0      0   
Wirz, Mr. Albert                                male  27.00000      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1      1   
...                                              ...       ...    ...    ...   
Spector, Mr. Woolf                              male  30.27259      0      0   
Oliva y Ocana, Dona. Fermina                  female  39.00000      0      0   
Saether, Mr. Simon Sivertsen                    male  38.50000      0      0   
Ware, Mr. Frederick                             male  30.27259      0      0   
Peter, Master. Michael J                        male  30.27259      1      1   

                                                          Ticket      Fare  \
Name                                                                         
Kelly, Mr. James                                          330911    7.8292   
Wilkes, Mrs. James (Ellen Needs)                          363272    7.0000   
Myles, Mr. Thomas Francis                                 240276    9.6875   
Wirz, Mr. Albert                                          315154    8.6625   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)             3101298   12.2875   
...                                                          ...       ...   
Spector, Mr. Woolf                                     A.5. 3236    8.0500   
Oliva y Ocana, Dona. Fermina                            PC 17758  108.9000   
Saether, Mr. Simon Sivertsen                  SOTON/O.Q. 3101262    7.2500   
Ware, Mr. Frederick                                       359309    8.0500   
Peter, Master. Michael J                                    2668   22.3583   

                                             Cabin Embarked  
Name                                                         
Kelly, Mr. James                                          Q  
Wilkes, Mrs. James (Ellen Needs)                          S  
Myles, Mr. Thomas Francis                                 Q  
Wirz, Mr. Albert                                          S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)              S  
...                                            ...      ...  
Spector, Mr. Woolf                             C78        S  
Oliva y Ocana, Dona. Fermina                  C105        C  
Saether, Mr. Simon Sivertsen                  C105        S  
Ware, Mr. Frederick                           C105        S  
Peter, Master. Michael J                      C105        C  

[418 rows x 11 columns]

In [113]:
a.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [114]:
a

PassengerId  Survived  Pclass  \
Name                                                                          
Kelly, Mr. James                                      892         0       3   
Wilkes, Mrs. James (Ellen Needs)                      893         1       3   
Myles, Mr. Thomas Francis                             894         0       2   
Wirz, Mr. Albert                                      895         0       3   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)          896         1       3   
...                                                   ...       ...     ...   
Spector, Mr. Woolf                                   1305         0       3   
Oliva y Ocana, Dona. Fermina                         1306         1       1   
Saether, Mr. Simon Sivertsen                         1307         0       3   
Ware, Mr. Frederick                                  1308         0       3   
Peter, Master. Michael J                             1309         0       3   

                                                 Sex       Age  SibSp  Parch  \
Name                                                                           
Kelly, Mr. James                                male  34.50000      0      0   
Wilkes, Mrs. James (Ellen Needs)              female  47.00000      1      0   
Myles, Mr. Thomas Francis                       male  62.00000      0      0   
Wirz, Mr. Albert                                male  27.00000      0      0   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.00000      1      1   
...                                              ...       ...    ...    ...   
Spector, Mr. Woolf                              male  30.27259      0      0   
Oliva y Ocana, Dona. Fermina                  female  39.00000      0      0   
Saether, Mr. Simon Sivertsen                    male  38.50000      0      0   
Ware, Mr. Frederick                             male  30.27259      0      0   
Peter, Master. Michael J                        male  30.27259      1      1   

                                                          Ticket      Fare  \
Name                                                                         
Kelly, Mr. James                                          330911    7.8292   
Wilkes, Mrs. James (Ellen Needs)                          363272    7.0000   
Myles, Mr. Thomas Francis                                 240276    9.6875   
Wirz, Mr. Albert                                          315154    8.6625   
Hirvonen, Mrs. Alexander (Helga E Lindqvist)             3101298   12.2875   
...                                                          ...       ...   
Spector, Mr. Woolf                                     A.5. 3236    8.0500   
Oliva y Ocana, Dona. Fermina                            PC 17758  108.9000   
Saether, Mr. Simon Sivertsen                  SOTON/O.Q. 3101262    7.2500   
Ware, Mr. Frederick                                       359309    8.0500   
Peter, Master. Michael J                                    2668   22.3583   

                                             Cabin Embarked  
Name                                                         
Kelly, Mr. James                                          Q  
Wilkes, Mrs. James (Ellen Needs)                          S  
Myles, Mr. Thomas Francis                                 Q  
Wirz, Mr. Albert                                          S  
Hirvonen, Mrs. Alexander (Helga E Lindqvist)              S  
...                                            ...      ...  
Spector, Mr. Woolf                             C78        S  
Oliva y Ocana, Dona. Fermina                  C105        C  
Saether, Mr. Simon Sivertsen                  C105        S  
Ware, Mr. Frederick                           C105        S  
Peter, Master. Michael J                      C105        C  

[418 rows x 11 columns]

In [119]:
data=a[(a['Fare']<=7.0000)]
data

PassengerId  Survived  Pclass     Sex  \
Name                                                                            
Wilkes, Mrs. James (Ellen Needs)                893         1       3  female   
Olsen, Master. Artur Karl                       913         0       3    male   
Thomas, Mr. John                               1008         0       3    male   
Thomas, Mr. Charles P                          1025         0       3    male   
Pearce, Mr. Ernest                             1055         0       3    male   
Wiklund, Mr. Karl Johan                        1124         0       3    male   
Chisholm, Mr. Roderick Robert Crispin          1158         0       1    male   
Daly, Miss. Margaret Marcella Maggie""         1183         1       3  female   
Ismay, Mr. Joseph Bruce                        1264         0       1    male   

                                             Age  SibSp  Parch   Ticket  \
Name                                                                      
Wilkes, Mrs. James (Ellen Needs)        47.00000      1      0   363272   
Olsen, Master. Artur Karl                9.00000      0      1  C 17368   
Thomas, Mr. John                        30.27259      0      0     2681   
Thomas, Mr. Charles P                   30.27259      1      0     2621   
Pearce, Mr. Ernest                      30.27259      0      0   343271   
Wiklund, Mr. Karl Johan                 21.00000      1      0  3101266   
Chisholm, Mr. Roderick Robert Crispin   30.27259      0      0   112051   
Daly, Miss. Margaret Marcella Maggie""  30.00000      0      0   382650   
Ismay, Mr. Joseph Bruce                 49.00000      0      0   112058   

                                          Fare        Cabin Embarked  
Name                                                                  
Wilkes, Mrs. James (Ellen Needs)        7.0000                     S  
Olsen, Master. Artur Karl               3.1708          E31        S  
Thomas, Mr. John                        6.4375      C55 C57        C  
Thomas, Mr. Charles P                   6.4375          C51        C  
Pearce, Mr. Ernest                      7.0000          D22        S  
Wiklund, Mr. Karl Johan                 6.4958          F33        S  
Chisholm, Mr. Roderick Robert Crispin   0.0000          C89        S  
Daly, Miss. Margaret Marcella Maggie""  6.9500        F E46        Q  
Ismay, Mr. Joseph Bruce                 0.0000  B52 B54 B56        S

In [123]:
data=a[(a['SibSp']==0)]
data

PassengerId  Survived  Pclass     Sex  \
Name                                                                    
Kelly, Mr. James                        892         0       3    male   
Myles, Mr. Thomas Francis               894         0       2    male   
Wirz, Mr. Albert                        895         0       3    male   
Svensson, Mr. Johan Cervin              897         0       3    male   
Connolly, Miss. Kate                    898         1       3  female   
...                                     ...       ...     ...     ...   
Henriksson, Miss. Jenny Lovisa         1304         1       3  female   
Spector, Mr. Woolf                     1305         0       3    male   
Oliva y Ocana, Dona. Fermina           1306         1       1  female   
Saether, Mr. Simon Sivertsen           1307         0       3    male   
Ware, Mr. Frederick                    1308         0       3    male   

                                     Age  SibSp  Parch              Ticket  \
Name                                                                         
Kelly, Mr. James                34.50000      0      0              330911   
Myles, Mr. Thomas Francis       62.00000      0      0              240276   
Wirz, Mr. Albert                27.00000      0      0              315154   
Svensson, Mr. Johan Cervin      14.00000      0      0                7538   
Connolly, Miss. Kate            30.00000      0      0              330972   
...                                  ...    ...    ...                 ...   
Henriksson, Miss. Jenny Lovisa  28.00000      0      0              347086   
Spector, Mr. Woolf              30.27259      0      0           A.5. 3236   
Oliva y Ocana, Dona. Fermina    39.00000      0      0            PC 17758   
Saether, Mr. Simon Sivertsen    38.50000      0      0  SOTON/O.Q. 3101262   
Ware, Mr. Frederick             30.27259      0      0              359309   

                                    Fare Cabin Embarked  
Name                                                     
Kelly, Mr. James                  7.8292              Q  
Myles, Mr. Thomas Francis         9.6875              Q  
Wirz, Mr. Albert                  8.6625              S  
Svensson, Mr. Johan Cervin        9.2250              S  
Connolly, Miss. Kate              7.6292              Q  
...                                  ...   ...      ...  
Henriksson, Miss. Jenny Lovisa    7.7750   C78        S  
Spector, Mr. Woolf                8.0500   C78        S  
Oliva y Ocana, Dona. Fermina    108.9000  C105        C  
Saether, Mr. Simon Sivertsen      7.2500  C105        S  
Ware, Mr. Frederick               8.0500  C105        S  

[283 rows x 11 columns]